"""Friendly default names for new sessions.

A new session needs a default name. ``session-1``/``session-2`` is forgettable and,
now that sessions are tracked and shared by ``<github-id(s)>/<name>``, two people
each starting ``session-1`` produces confusingly similar entries. Instead we pick a
random, positive, harmless English word — easy to remember and unlikely to clash. The
user can still rename or type their own at the new-session prompt.

The list is deliberately **positive, common, and concrete** — cheerful everyday nouns
(gardens, flowers, fruit, gemstones, friendly animals, light and nature, plus a few
upbeat abstractions like ``harmony`` and ``joy``) — so a generated name is familiar,
easy to say and type, pleasant in tone, and never charged, branded, or negative.
"""

from __future__ import annotations

import random

# A long list of positive, common one-word nouns. Kept sorted and lowercase; all
# sanitize to themselves so a picked word is also a valid worktree/branch name component.
SESSION_WORDS: tuple[str, ...] = (
    "amber",
    "angel",
    "anthem",
    "apple",
    "apricot",
    "aurora",
    "beacon",
    "berry",
    "blessing",
    "bloom",
    "blossom",
    "bluebell",
    "bluebird",
    "bounty",
    "bouquet",
    "breeze",
    "brook",
    "bubble",
    "buttercup",
    "butterfly",
    "candle",
    "carol",
    "champion",
    "charm",
    "cheer",
    "cherry",
    "cherub",
    "chorus",
    "clover",
    "cocoa",
    "comet",
    "comfort",
    "cookie",
    "coral",
    "cottage",
    "courage",
    "cove",
    "crystal",
    "cupcake",
    "daffodil",
    "dahlia",
    "daisy",
    "dawn",
    "daydream",
    "delight",
    "dewdrop",
    "diamond",
    "dolphin",
    "dove",
    "dream",
    "ember",
    "emerald",
    "fawn",
    "feast",
    "fern",
    "festival",
    "fiesta",
    "firefly",
    "fireside",
    "flame",
    "flower",
    "fortune",
    "fountain",
    "freedom",
    "friend",
    "galaxy",
    "garden",
    "garland",
    "gazelle",
    "gem",
    "gift",
    "glade",
    "gleam",
    "glee",
    "glory",
    "glow",
    "gold",
    "goldfinch",
    "goodness",
    "grace",
    "grove",
    "halo",
    "harbor",
    "harmony",
    "harvest",
    "haven",
    "hazel",
    "hearth",
    "heron",
    "hill",
    "honey",
    "honeybee",
    "hope",
    "hummingbird",
    "iris",
    "island",
    "ivory",
    "ivy",
    "jade",
    "jasmine",
    "jewel",
    "joy",
    "jubilee",
    "juniper",
    "keepsake",
    "kindness",
    "kitten",
    "koala",
    "lagoon",
    "lantern",
    "lark",
    "laughter",
    "laurel",
    "lavender",
    "leaf",
    "liberty",
    "lighthouse",
    "lilac",
    "lily",
    "lotus",
    "lullaby",
    "magnolia",
    "mango",
    "maple",
    "marigold",
    "marvel",
    "meadow",
    "medley",
    "melody",
    "mint",
    "miracle",
    "moon",
    "moonbeam",
    "myrtle",
    "nectar",
    "nectarine",
    "nest",
    "nightingale",
    "nutmeg",
    "oasis",
    "olive",
    "opal",
    "orchard",
    "orchid",
    "otter",
    "palm",
    "panda",
    "pansy",
    "paradise",
    "peace",
    "peach",
    "pear",
    "pearl",
    "penguin",
    "peony",
    "petal",
    "phoenix",
    "picnic",
    "pine",
    "pomegranate",
    "poppy",
    "prairie",
    "primrose",
    "promise",
    "quilt",
    "radiance",
    "rainbow",
    "ribbon",
    "ripple",
    "river",
    "robin",
    "rose",
    "ruby",
    "sage",
    "sapphire",
    "seashell",
    "serenade",
    "serenity",
    "shore",
    "silver",
    "sky",
    "snowdrop",
    "songbird",
    "spark",
    "sparrow",
    "splendor",
    "spring",
    "sprout",
    "star",
    "starfish",
    "sugar",
    "summit",
    "sunbeam",
    "sundae",
    "sunflower",
    "sunrise",
    "sunset",
    "sunshine",
    "swan",
    "thyme",
    "topaz",
    "treasure",
    "triumph",
    "trophy",
    "tulip",
    "twilight",
    "unity",
    "valley",
    "vanilla",
    "velvet",
    "victory",
    "violet",
    "virtue",
    "waterfall",
    "willow",
    "wisdom",
    "wonder",
    "zenith",
    "zest",
    "zinnia",
)


def random_session_name(taken: set[str], *, choice=random.choice) -> str:
    """A friendly random word not already in ``taken`` (a set of sanitized names).

    ``choice`` is injectable so tests can make the pick deterministic. If every word
    is taken — vanishingly unlikely with this many — fall back to a numeric suffix so a
    name is always returned."""
    available = [w for w in SESSION_WORDS if w not in taken]
    if available:
        return choice(available)
    base = choice(SESSION_WORDS)
    n = 2
    while f"{base}-{n}" in taken:
        n += 1
    return f"{base}-{n}"
