"""Friendly default names for new sessions.

A new session needs a default name. ``session-1``/``session-2`` is forgettable and,
now that sessions are tracked and shared by ``<github-id(s)>/<name>``, two people
each starting ``session-1`` produces confusingly similar entries. Instead we pick a
random neutral, harmless English word — easy to remember and unlikely to clash. The
user can still rename or type their own at the new-session prompt.

The list is deliberately bland (nature, animals, plants, weather, materials, places)
so a generated name is never charged, branded, or otherwise loaded.
"""

from __future__ import annotations

import random

# A long list of neutral one-word nouns. Kept sorted and lowercase; all sanitize to
# themselves so a picked word is also a valid worktree/branch name component.
SESSION_WORDS: tuple[str, ...] = (
    "acorn",
    "alder",
    "almond",
    "amber",
    "anchor",
    "apple",
    "apricot",
    "arch",
    "ash",
    "aspen",
    "atlas",
    "aurora",
    "autumn",
    "azure",
    "bamboo",
    "basil",
    "bay",
    "beacon",
    "bean",
    "bear",
    "beech",
    "berry",
    "birch",
    "bison",
    "blossom",
    "bluff",
    "bramble",
    "brass",
    "breeze",
    "bridge",
    "brook",
    "buffalo",
    "butter",
    "cabin",
    "cactus",
    "camphor",
    "canyon",
    "cape",
    "cedar",
    "cherry",
    "chestnut",
    "cinder",
    "citron",
    "clay",
    "clover",
    "cloud",
    "coast",
    "cobalt",
    "comet",
    "copper",
    "coral",
    "cove",
    "crane",
    "creek",
    "crocus",
    "crystal",
    "cypress",
    "daffodil",
    "dahlia",
    "daisy",
    "dale",
    "dawn",
    "delta",
    "dew",
    "dune",
    "eagle",
    "ember",
    "fable",
    "falcon",
    "fawn",
    "fennel",
    "fern",
    "fjord",
    "flax",
    "flint",
    "forest",
    "fox",
    "frost",
    "garnet",
    "geode",
    "ginger",
    "glade",
    "glacier",
    "granite",
    "grove",
    "harbor",
    "harvest",
    "hawk",
    "hazel",
    "heath",
    "heron",
    "hickory",
    "hollow",
    "honey",
    "iris",
    "island",
    "ivory",
    "ivy",
    "jade",
    "jasmine",
    "juniper",
    "kelp",
    "lagoon",
    "lake",
    "lantern",
    "larch",
    "lark",
    "laurel",
    "leaf",
    "ledge",
    "lemon",
    "lichen",
    "lilac",
    "lily",
    "linden",
    "lotus",
    "lupine",
    "lynx",
    "maple",
    "marble",
    "marigold",
    "meadow",
    "mesa",
    "millet",
    "mint",
    "mist",
    "moss",
    "moth",
    "mulberry",
    "nectar",
    "nettle",
    "oak",
    "oasis",
    "ocean",
    "olive",
    "onyx",
    "opal",
    "orchard",
    "orchid",
    "otter",
    "owl",
    "pampas",
    "pansy",
    "pearl",
    "pebble",
    "pepper",
    "petal",
    "pewter",
    "pine",
    "pippin",
    "plover",
    "plum",
    "pollen",
    "pond",
    "poplar",
    "poppy",
    "prairie",
    "quail",
    "quartz",
    "quince",
    "rapids",
    "raven",
    "reed",
    "ridge",
    "rill",
    "river",
    "robin",
    "rowan",
    "rye",
    "saffron",
    "sage",
    "sand",
    "sapphire",
    "sedge",
    "shale",
    "shore",
    "silver",
    "sienna",
    "slate",
    "snow",
    "sorrel",
    "spruce",
    "starling",
    "stone",
    "stork",
    "stream",
    "summit",
    "sundew",
    "sunset",
    "swallow",
    "sycamore",
    "tansy",
    "teal",
    "thicket",
    "thistle",
    "thyme",
    "timber",
    "topaz",
    "trail",
    "tulip",
    "tundra",
    "valley",
    "velvet",
    "vine",
    "violet",
    "walnut",
    "willow",
    "wren",
    "yarrow",
    "yew",
    "zephyr",
    "zinnia",
)


def random_session_name(taken: set[str], *, choice=random.choice) -> str:
    """A friendly random word not already in ``taken`` (a set of sanitized names).

    ``choice`` is injectable so tests can make the pick deterministic. If every word
    is taken — vanishingly unlikely with this many — fall back to a numeric suffix so a
    name is always returned."""
    available = [w for w in SESSION_WORDS if w not in taken]
    if available:
        return choice(available)
    base = choice(SESSION_WORDS)
    n = 2
    while f"{base}-{n}" in taken:
        n += 1
    return f"{base}-{n}"
