"""Friendly default names for new sessions.

A new session needs a default name. ``session-1``/``session-2`` is forgettable and,
now that sessions are tracked and shared by ``<github-id(s)>/<name>``, two people
each starting ``session-1`` produces confusingly similar entries. Instead we pick a
random neutral, harmless English word — easy to remember and unlikely to clash. The
user can still rename or type their own at the new-session prompt.

The list is deliberately **common and bland** (everyday animals, plants, food, nature,
weather, materials, household objects) so a generated name is familiar, easy to say and
type, and never charged, branded, or otherwise loaded.
"""

from __future__ import annotations

import random

# A long list of common, everyday one-word nouns. Kept sorted and lowercase; all
# sanitize to themselves so a picked word is also a valid worktree/branch name component.
SESSION_WORDS: tuple[str, ...] = (
    "acorn",
    "almond",
    "amber",
    "anchor",
    "ant",
    "apple",
    "apricot",
    "arrow",
    "ash",
    "autumn",
    "badger",
    "bamboo",
    "banana",
    "basil",
    "basket",
    "beach",
    "bean",
    "bear",
    "beaver",
    "bee",
    "beetle",
    "bell",
    "berry",
    "birch",
    "bird",
    "bison",
    "bottle",
    "boulder",
    "brass",
    "breeze",
    "brick",
    "bridge",
    "brook",
    "bubble",
    "bucket",
    "buffalo",
    "button",
    "cabin",
    "cactus",
    "camel",
    "candle",
    "canyon",
    "carrot",
    "castle",
    "cat",
    "cave",
    "cedar",
    "cherry",
    "clay",
    "cloud",
    "clover",
    "coast",
    "comet",
    "compass",
    "copper",
    "coral",
    "corn",
    "cottage",
    "cotton",
    "cow",
    "coyote",
    "crab",
    "crane",
    "creek",
    "cricket",
    "crow",
    "crystal",
    "daisy",
    "dawn",
    "deer",
    "desert",
    "dew",
    "diamond",
    "dolphin",
    "donkey",
    "dove",
    "dragon",
    "duck",
    "dune",
    "dusk",
    "eagle",
    "eel",
    "elephant",
    "elk",
    "ember",
    "emerald",
    "falcon",
    "fawn",
    "feather",
    "fern",
    "finch",
    "fire",
    "fish",
    "flame",
    "flamingo",
    "flower",
    "forest",
    "fountain",
    "fox",
    "frog",
    "frost",
    "garden",
    "garnet",
    "ginger",
    "glacier",
    "glass",
    "goat",
    "gold",
    "goose",
    "grape",
    "grass",
    "gravel",
    "grove",
    "hammer",
    "harbor",
    "hare",
    "harvest",
    "hawk",
    "hazel",
    "heather",
    "hen",
    "heron",
    "hill",
    "hollow",
    "honey",
    "horse",
    "hound",
    "ice",
    "iris",
    "iron",
    "island",
    "ivory",
    "ivy",
    "jade",
    "jaguar",
    "jasmine",
    "jay",
    "juniper",
    "kettle",
    "kitten",
    "koala",
    "ladder",
    "lagoon",
    "lake",
    "lamb",
    "lantern",
    "lark",
    "laurel",
    "lava",
    "leaf",
    "lemon",
    "leopard",
    "lilac",
    "lily",
    "lime",
    "linen",
    "lion",
    "lizard",
    "llama",
    "lobster",
    "lotus",
    "lynx",
    "magnet",
    "mango",
    "maple",
    "marble",
    "meadow",
    "melon",
    "mint",
    "mirror",
    "mist",
    "mole",
    "monkey",
    "moon",
    "moose",
    "moss",
    "moth",
    "mountain",
    "mouse",
    "mushroom",
    "needle",
    "nest",
    "nutmeg",
    "oak",
    "ocean",
    "olive",
    "onion",
    "opal",
    "orange",
    "orchard",
    "orchid",
    "otter",
    "owl",
    "ox",
    "palm",
    "panda",
    "pansy",
    "paper",
    "parrot",
    "peach",
    "peacock",
    "pear",
    "pearl",
    "pebble",
    "pelican",
    "pencil",
    "penguin",
    "pepper",
    "petal",
    "pigeon",
    "pillow",
    "pine",
    "pineapple",
    "plum",
    "pond",
    "pony",
    "poppy",
    "prairie",
    "puddle",
    "pumpkin",
    "puppy",
    "quail",
    "quartz",
    "quince",
    "rabbit",
    "raccoon",
    "rain",
    "rainbow",
    "raven",
    "reed",
    "ribbon",
    "ridge",
    "river",
    "robin",
    "rock",
    "rooster",
    "rose",
    "ruby",
    "rye",
    "saddle",
    "sage",
    "salmon",
    "sand",
    "sapphire",
    "seal",
    "seed",
    "shark",
    "sheep",
    "shell",
    "shore",
    "silver",
    "sky",
    "slate",
    "sloth",
    "snail",
    "snake",
    "snow",
    "spark",
    "sparrow",
    "spider",
    "spruce",
    "squirrel",
    "star",
    "steel",
    "stone",
    "stork",
    "storm",
    "stream",
    "summit",
    "sunflower",
    "sunset",
    "swallow",
    "swan",
    "table",
    "teal",
    "thistle",
    "thunder",
    "tiger",
    "timber",
    "toad",
    "tomato",
    "topaz",
    "trail",
    "tree",
    "trout",
    "tulip",
    "tundra",
    "turtle",
    "umbrella",
    "valley",
    "velvet",
    "village",
    "vine",
    "violet",
    "wagon",
    "walnut",
    "walrus",
    "wasp",
    "water",
    "wave",
    "weasel",
    "whale",
    "wheat",
    "willow",
    "wind",
    "window",
    "wolf",
    "wood",
    "woodpecker",
    "wren",
    "yarn",
    "yew",
    "zebra",
    "zinnia",
)


def random_session_name(taken: set[str], *, choice=random.choice) -> str:
    """A friendly random word not already in ``taken`` (a set of sanitized names).

    ``choice`` is injectable so tests can make the pick deterministic. If every word
    is taken — vanishingly unlikely with this many — fall back to a numeric suffix so a
    name is always returned."""
    available = [w for w in SESSION_WORDS if w not in taken]
    if available:
        return choice(available)
    base = choice(SESSION_WORDS)
    n = 2
    while f"{base}-{n}" in taken:
        n += 1
    return f"{base}-{n}"
