"""Repository metrics extracted from aGiTrack commit metadata (#54)."""

from agitrack.metrics.collect import CommitStat, Dashboard, build_dashboard, collect_commit_stats
from agitrack.metrics.daemon import (
    clear_handshake,
    dashboard_daemon_status,
    handshake_path,
    log_path,
    read_handshake,
    run_dashboard_daemon,
    running_handshake,
    spawn_dashboard_daemon,
    start_dashboard_daemon,
    stop_dashboard_daemon,
    wait_for_handshake,
)
from agitrack.metrics.render import render_dashboard
from agitrack.metrics.server import (
    advertised_host,
    bind_scanning,
    build_server,
    dashboard_url,
    default_bind_host,
    exposure_note,
    is_remote_session,
    open_dashboard_in_browser,
    remote_access_help,
    remote_browser_hint,
    serve_dashboard,
    ssh_forward_command,
)
from agitrack.metrics.web import dashboard_data, render_html

__all__ = [
    "CommitStat",
    "Dashboard",
    "advertised_host",
    "bind_scanning",
    "build_dashboard",
    "build_server",
    "clear_handshake",
    "collect_commit_stats",
    "dashboard_daemon_status",
    "dashboard_data",
    "dashboard_url",
    "default_bind_host",
    "exposure_note",
    "handshake_path",
    "is_remote_session",
    "log_path",
    "open_dashboard_in_browser",
    "read_handshake",
    "remote_access_help",
    "remote_browser_hint",
    "render_dashboard",
    "render_html",
    "run_dashboard_daemon",
    "running_handshake",
    "serve_dashboard",
    "spawn_dashboard_daemon",
    "ssh_forward_command",
    "start_dashboard_daemon",
    "stop_dashboard_daemon",
    "wait_for_handshake",
]
